"""Add users

Revision ID: 9a6f70dcc851
Revises: ce660fc4542e
Create Date: 2023-02-24 18:00:42.014494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table
from passlib.hash import pbkdf2_sha256
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '9a6f70dcc851'
down_revision = 'ce660fc4542e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = table('users',
                  sa.Column('id', sa.Integer(), nullable=False),
                  sa.Column('username', sa.String(), nullable=False),
                  sa.Column('password_hashed', sa.String(), nullable=False),
                  sa.Column('role', sa.String(), nullable=True),
                  sa.Column('created_at', sa.DateTime(), nullable=True),
                  sa.Column('created_by', sa.Integer(), nullable=True),
                  sa.Column('modifed_at', sa.DateTime(), nullable=True),
                  sa.Column('modifed_by', sa.Integer(), nullable=True)
                  )
    op.bulk_insert(users,
                   [
                       {
                           'id': 1,
                           'username': 'admin',
                           'password_hashed': pbkdf2_sha256.hash('admin'),
                           'role': 'admin',
                           'created_at': datetime.utcnow(),
                           'created_by': 1,
                           'modifed_at': datetime.utcnow(),
                           'modifed_by': 1
                       }
                   ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
